### ISSUE TITLE
Make code resilient against out of order packages

### ISSUE THREAD

**Issue by perguth** [pguth/peertransfer#15]
<pre>
Receving chunk #1088 of 1093
bundle.js:57 Receving chunk #1093 of 1093
bundle.js:255 'webkitURL' is deprecated. Please use 'URL' instead.
<b>bundle.js:57 blob:http%3A//pguth.github.io/edfd3656-6120-4244-a0df-3bb34d81ff92</b>
bundle.js:57 Receving chunk #1089 of 1093
bundle.js:57 Receving chunk #1090 of 1093
bundle.js:57 Receving chunk #1091 of 1093
bundle.js:57 Receving chunk #1092 of 1093
</pre>

Download starts before file transfer finishes.

**Comment by pguth** [comment]
<pre>
Receving chunk #1088 of 1093
bundle.js:57 Receving chunk #1093 of 1093
bundle.js:255 'webkitURL' is deprecated. Please use 'URL' instead.
<b>bundle.js:57 blob:http%3A//pguth.github.io/edfd3656-6120-4244-a0df-3bb34d81ff92</b>
bundle.js:57 Receving chunk #1089 of 1093
bundle.js:57 Receving chunk #1090 of 1093
bundle.js:57 Receving chunk #1091 of 1093
bundle.js:57 Receving chunk #1092 of 1093
</pre>
Download starts before file transfer finishes.
