### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by upsteer** [pguth/peertransfer#37]
How do I actually run the project?
I have successfully cloned the project.
But I don't see any server.js file to run a server for file transfer.

**Comment by perguth** [comment]
I am currently rewrite the codebase. It will behave more in the standard way you would expect from a node module. At some point I'll update the README.

**Comment by perguth** [comment]
Ok, now peertransfer only requires you to run `npm start` and then spins up a webserver on [localhost:9966](http://localhost:9966).

**Comment by perguth** [comment]
@upsteer Peertransfer does not need to run code server side. You can just build it (`npm run build`) and then deploy the files that got put into `/build`.
