### ISSUE TITLE
Problem loading page

### ISSUE THREAD

**Issue by quarck-project** [pguth/peertransfer#45]
peertransfer@2.1.2 start /root/peertransfer
> [[ $NODE_EVN = production ]] && npm run prod || npm run dev

sh: 1: [[: not found

> peertransfer@2.1.2 dev /root/peertransfer
> signalhub listen -p 7000 & budo --live --host localhost index.js:bundle.js -- -t envify

signalhub listening on port 7000
[0000] info  Server running at http://localhost:9966/ (connect)
[0000] info  LiveReload running
[0002] 2090ms     3.6MB (browserify)

But cant connect to webpage

**Comment by perguth** [comment]
Windows?

**Comment by quarck-project** [comment]
> Windows?

ubuntu 16.04

**Comment by perguth** [comment]
Fixed in https://github.com/perguth/peertransfer/commit/4f2a9ea6278a6df4203cf30532a1d38db16e3224
