### ISSUE TITLE
Save in chunks (to allow for bigger files)

### ISSUE THREAD

**Issue by perguth** [pguth/peertransfer#7]
- [ ] [Query storage available](https://developers.google.com/chrome/whitepapers/storage?csw=1#query)
- [ ] [React accordingly](https://developers.google.com/chrome/whitepapers/storage?csw=1#table): Temporary or persistent storage

[Source](http://stackoverflow.com/a/20639136/2924001)

**Comment by pguth** [comment]
[ ] [Query storage available](https://developers.google.com/chrome/whitepapers/storage?csw=1#query)
[ ] [React accordingly](https://developers.google.com/chrome/whitepapers/storage?csw=1#table)

[Source](http://stackoverflow.com/a/20639136/2924001)
